package com.lgw.po;

import java.util.Date;

public class City {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_city.cid
     *
     * @mbg.generated
     */
    private String cid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_city.cname
     *
     * @mbg.generated
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_city.xmodifier
     *
     * @mbg.generated
     */
    private String xmodifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_city.xmodifiytime
     *
     * @mbg.generated
     */
    private Date xmodifiytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_city.xcreator
     *
     * @mbg.generated
     */
    private String xcreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_city.xcreatetime
     *
     * @mbg.generated
     */
    private Date xcreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_city.cid
     *
     * @return the value of b_city.cid
     *
     * @mbg.generated
     */
    public String getCid() {
        return cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_city.cid
     *
     * @param cid the value for b_city.cid
     *
     * @mbg.generated
     */
    public void setCid(String cid) {
        this.cid = cid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_city.cname
     *
     * @return the value of b_city.cname
     *
     * @mbg.generated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_city.cname
     *
     * @param cname the value for b_city.cname
     *
     * @mbg.generated
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_city.xmodifier
     *
     * @return the value of b_city.xmodifier
     *
     * @mbg.generated
     */
    public String getXmodifier() {
        return xmodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_city.xmodifier
     *
     * @param xmodifier the value for b_city.xmodifier
     *
     * @mbg.generated
     */
    public void setXmodifier(String xmodifier) {
        this.xmodifier = xmodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_city.xmodifiytime
     *
     * @return the value of b_city.xmodifiytime
     *
     * @mbg.generated
     */
    public Date getXmodifiytime() {
        return xmodifiytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_city.xmodifiytime
     *
     * @param xmodifiytime the value for b_city.xmodifiytime
     *
     * @mbg.generated
     */
    public void setXmodifiytime(Date xmodifiytime) {
        this.xmodifiytime = xmodifiytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_city.xcreator
     *
     * @return the value of b_city.xcreator
     *
     * @mbg.generated
     */
    public String getXcreator() {
        return xcreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_city.xcreator
     *
     * @param xcreator the value for b_city.xcreator
     *
     * @mbg.generated
     */
    public void setXcreator(String xcreator) {
        this.xcreator = xcreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_city.xcreatetime
     *
     * @return the value of b_city.xcreatetime
     *
     * @mbg.generated
     */
    public Date getXcreatetime() {
        return xcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_city.xcreatetime
     *
     * @param xcreatetime the value for b_city.xcreatetime
     *
     * @mbg.generated
     */
    public void setXcreatetime(Date xcreatetime) {
        this.xcreatetime = xcreatetime;
    }
}