package com.lgw.po;

public class CompanyWithBLOBs extends Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.brief
     *
     * @mbg.generated
     */
    private String brief;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.context
     *
     * @mbg.generated
     */
    private String context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.brief
     *
     * @return the value of p_company.brief
     *
     * @mbg.generated
     */
    public String getBrief() {
        return brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.brief
     *
     * @param brief the value for p_company.brief
     *
     * @mbg.generated
     */
    public void setBrief(String brief) {
        this.brief = brief;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.context
     *
     * @return the value of p_company.context
     *
     * @mbg.generated
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.context
     *
     * @param context the value for p_company.context
     *
     * @mbg.generated
     */
    public void setContext(String context) {
        this.context = context;
    }
}