package com.lgw.po;

import java.util.Date;

public class Company {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.companyid
     *
     * @mbg.generated
     */
    private String companyid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.cname
     *
     * @mbg.generated
     */
    private String cname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.imgid
     *
     * @mbg.generated
     */
    private String imgid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.www
     *
     * @mbg.generated
     */
    private String www;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.comparea
     *
     * @mbg.generated
     */
    private String comparea;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.compsize
     *
     * @mbg.generated
     */
    private String compsize;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.compstage
     *
     * @mbg.generated
     */
    private String compstage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.modifier
     *
     * @mbg.generated
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.modifytime
     *
     * @mbg.generated
     */
    private Date modifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.lgname
     *
     * @mbg.generated
     */
    private String lgname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.lgpwd
     *
     * @mbg.generated
     */
    private String lgpwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.blank1
     *
     * @mbg.generated
     */
    private String blank1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.blank2
     *
     * @mbg.generated
     */
    private String blank2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.blank3
     *
     * @mbg.generated
     */
    private String blank3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_company.blank4
     *
     * @mbg.generated
     */
    private String blank4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.companyid
     *
     * @return the value of p_company.companyid
     *
     * @mbg.generated
     */
    public String getCompanyid() {
        return companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.companyid
     *
     * @param companyid the value for p_company.companyid
     *
     * @mbg.generated
     */
    public void setCompanyid(String companyid) {
        this.companyid = companyid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.cname
     *
     * @return the value of p_company.cname
     *
     * @mbg.generated
     */
    public String getCname() {
        return cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.cname
     *
     * @param cname the value for p_company.cname
     *
     * @mbg.generated
     */
    public void setCname(String cname) {
        this.cname = cname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.imgid
     *
     * @return the value of p_company.imgid
     *
     * @mbg.generated
     */
    public String getImgid() {
        return imgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.imgid
     *
     * @param imgid the value for p_company.imgid
     *
     * @mbg.generated
     */
    public void setImgid(String imgid) {
        this.imgid = imgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.www
     *
     * @return the value of p_company.www
     *
     * @mbg.generated
     */
    public String getWww() {
        return www;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.www
     *
     * @param www the value for p_company.www
     *
     * @mbg.generated
     */
    public void setWww(String www) {
        this.www = www;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.city
     *
     * @return the value of p_company.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.city
     *
     * @param city the value for p_company.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.comparea
     *
     * @return the value of p_company.comparea
     *
     * @mbg.generated
     */
    public String getComparea() {
        return comparea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.comparea
     *
     * @param comparea the value for p_company.comparea
     *
     * @mbg.generated
     */
    public void setComparea(String comparea) {
        this.comparea = comparea;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.compsize
     *
     * @return the value of p_company.compsize
     *
     * @mbg.generated
     */
    public String getCompsize() {
        return compsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.compsize
     *
     * @param compsize the value for p_company.compsize
     *
     * @mbg.generated
     */
    public void setCompsize(String compsize) {
        this.compsize = compsize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.compstage
     *
     * @return the value of p_company.compstage
     *
     * @mbg.generated
     */
    public String getCompstage() {
        return compstage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.compstage
     *
     * @param compstage the value for p_company.compstage
     *
     * @mbg.generated
     */
    public void setCompstage(String compstage) {
        this.compstage = compstage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.modifier
     *
     * @return the value of p_company.modifier
     *
     * @mbg.generated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.modifier
     *
     * @param modifier the value for p_company.modifier
     *
     * @mbg.generated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.modifytime
     *
     * @return the value of p_company.modifytime
     *
     * @mbg.generated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.modifytime
     *
     * @param modifytime the value for p_company.modifytime
     *
     * @mbg.generated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.creator
     *
     * @return the value of p_company.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.creator
     *
     * @param creator the value for p_company.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.createtime
     *
     * @return the value of p_company.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.createtime
     *
     * @param createtime the value for p_company.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.lgname
     *
     * @return the value of p_company.lgname
     *
     * @mbg.generated
     */
    public String getLgname() {
        return lgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.lgname
     *
     * @param lgname the value for p_company.lgname
     *
     * @mbg.generated
     */
    public void setLgname(String lgname) {
        this.lgname = lgname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.lgpwd
     *
     * @return the value of p_company.lgpwd
     *
     * @mbg.generated
     */
    public String getLgpwd() {
        return lgpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.lgpwd
     *
     * @param lgpwd the value for p_company.lgpwd
     *
     * @mbg.generated
     */
    public void setLgpwd(String lgpwd) {
        this.lgpwd = lgpwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.phone
     *
     * @return the value of p_company.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.phone
     *
     * @param phone the value for p_company.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.blank1
     *
     * @return the value of p_company.blank1
     *
     * @mbg.generated
     */
    public String getBlank1() {
        return blank1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.blank1
     *
     * @param blank1 the value for p_company.blank1
     *
     * @mbg.generated
     */
    public void setBlank1(String blank1) {
        this.blank1 = blank1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.blank2
     *
     * @return the value of p_company.blank2
     *
     * @mbg.generated
     */
    public String getBlank2() {
        return blank2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.blank2
     *
     * @param blank2 the value for p_company.blank2
     *
     * @mbg.generated
     */
    public void setBlank2(String blank2) {
        this.blank2 = blank2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.blank3
     *
     * @return the value of p_company.blank3
     *
     * @mbg.generated
     */
    public String getBlank3() {
        return blank3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.blank3
     *
     * @param blank3 the value for p_company.blank3
     *
     * @mbg.generated
     */
    public void setBlank3(String blank3) {
        this.blank3 = blank3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_company.blank4
     *
     * @return the value of p_company.blank4
     *
     * @mbg.generated
     */
    public String getBlank4() {
        return blank4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_company.blank4
     *
     * @param blank4 the value for p_company.blank4
     *
     * @mbg.generated
     */
    public void setBlank4(String blank4) {
        this.blank4 = blank4;
    }
}