package com.lgw.po;

import java.util.Date;

public class Defined {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_defined.did
     *
     * @mbg.generated
     */
    private String did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_defined.rid
     *
     * @mbg.generated
     */
    private String rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_defined.dtitle
     *
     * @mbg.generated
     */
    private String dtitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_defined.modifier
     *
     * @mbg.generated
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_defined.modifytime
     *
     * @mbg.generated
     */
    private Date modifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_defined.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_defined.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_defined.context
     *
     * @mbg.generated
     */
    private String context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_defined.did
     *
     * @return the value of p_defined.did
     *
     * @mbg.generated
     */
    public String getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_defined.did
     *
     * @param did the value for p_defined.did
     *
     * @mbg.generated
     */
    public void setDid(String did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_defined.rid
     *
     * @return the value of p_defined.rid
     *
     * @mbg.generated
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_defined.rid
     *
     * @param rid the value for p_defined.rid
     *
     * @mbg.generated
     */
    public void setRid(String rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_defined.dtitle
     *
     * @return the value of p_defined.dtitle
     *
     * @mbg.generated
     */
    public String getDtitle() {
        return dtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_defined.dtitle
     *
     * @param dtitle the value for p_defined.dtitle
     *
     * @mbg.generated
     */
    public void setDtitle(String dtitle) {
        this.dtitle = dtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_defined.modifier
     *
     * @return the value of p_defined.modifier
     *
     * @mbg.generated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_defined.modifier
     *
     * @param modifier the value for p_defined.modifier
     *
     * @mbg.generated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_defined.modifytime
     *
     * @return the value of p_defined.modifytime
     *
     * @mbg.generated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_defined.modifytime
     *
     * @param modifytime the value for p_defined.modifytime
     *
     * @mbg.generated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_defined.creator
     *
     * @return the value of p_defined.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_defined.creator
     *
     * @param creator the value for p_defined.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_defined.createtime
     *
     * @return the value of p_defined.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_defined.createtime
     *
     * @param createtime the value for p_defined.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_defined.context
     *
     * @return the value of p_defined.context
     *
     * @mbg.generated
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_defined.context
     *
     * @param context the value for p_defined.context
     *
     * @mbg.generated
     */
    public void setContext(String context) {
        this.context = context;
    }
}