package com.lgw.po;

import java.util.Date;

public class Education {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_education.eid
     *
     * @mbg.generated
     */
    private String eid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_education.rid
     *
     * @mbg.generated
     */
    private String rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_education.ename
     *
     * @mbg.generated
     */
    private String ename;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_education.major
     *
     * @mbg.generated
     */
    private String major;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_education.qual
     *
     * @mbg.generated
     */
    private String qual;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_education.eyear
     *
     * @mbg.generated
     */
    private Date eyear;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_education.modifier
     *
     * @mbg.generated
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_education.modifytime
     *
     * @mbg.generated
     */
    private Date modifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_education.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_education.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_education.eid
     *
     * @return the value of p_education.eid
     *
     * @mbg.generated
     */
    public String getEid() {
        return eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_education.eid
     *
     * @param eid the value for p_education.eid
     *
     * @mbg.generated
     */
    public void setEid(String eid) {
        this.eid = eid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_education.rid
     *
     * @return the value of p_education.rid
     *
     * @mbg.generated
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_education.rid
     *
     * @param rid the value for p_education.rid
     *
     * @mbg.generated
     */
    public void setRid(String rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_education.ename
     *
     * @return the value of p_education.ename
     *
     * @mbg.generated
     */
    public String getEname() {
        return ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_education.ename
     *
     * @param ename the value for p_education.ename
     *
     * @mbg.generated
     */
    public void setEname(String ename) {
        this.ename = ename;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_education.major
     *
     * @return the value of p_education.major
     *
     * @mbg.generated
     */
    public String getMajor() {
        return major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_education.major
     *
     * @param major the value for p_education.major
     *
     * @mbg.generated
     */
    public void setMajor(String major) {
        this.major = major;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_education.qual
     *
     * @return the value of p_education.qual
     *
     * @mbg.generated
     */
    public String getQual() {
        return qual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_education.qual
     *
     * @param qual the value for p_education.qual
     *
     * @mbg.generated
     */
    public void setQual(String qual) {
        this.qual = qual;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_education.eyear
     *
     * @return the value of p_education.eyear
     *
     * @mbg.generated
     */
    public Date getEyear() {
        return eyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_education.eyear
     *
     * @param eyear the value for p_education.eyear
     *
     * @mbg.generated
     */
    public void setEyear(Date eyear) {
        this.eyear = eyear;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_education.modifier
     *
     * @return the value of p_education.modifier
     *
     * @mbg.generated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_education.modifier
     *
     * @param modifier the value for p_education.modifier
     *
     * @mbg.generated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_education.modifytime
     *
     * @return the value of p_education.modifytime
     *
     * @mbg.generated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_education.modifytime
     *
     * @param modifytime the value for p_education.modifytime
     *
     * @mbg.generated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_education.creator
     *
     * @return the value of p_education.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_education.creator
     *
     * @param creator the value for p_education.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_education.createtime
     *
     * @return the value of p_education.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_education.createtime
     *
     * @param createtime the value for p_education.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}