package com.lgw.po;

import java.util.Date;

public class Recode {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrecode.jrid
     *
     * @mbg.generated
     */
    private String jrid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrecode.jobid
     *
     * @mbg.generated
     */
    private String jobid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrecode.sendid
     *
     * @mbg.generated
     */
    private String sendid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrecode.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrecode.style
     *
     * @mbg.generated
     */
    private String style;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrecode.modifier
     *
     * @mbg.generated
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrecode.modifytime
     *
     * @mbg.generated
     */
    private Date modifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrecode.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrecode.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrecode.blank1
     *
     * @mbg.generated
     */
    private String blank1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrecode.blank2
     *
     * @mbg.generated
     */
    private String blank2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrecode.blank3
     *
     * @mbg.generated
     */
    private String blank3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column jrecode.blank4
     *
     * @mbg.generated
     */
    private String blank4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrecode.jrid
     *
     * @return the value of jrecode.jrid
     *
     * @mbg.generated
     */
    public String getJrid() {
        return jrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrecode.jrid
     *
     * @param jrid the value for jrecode.jrid
     *
     * @mbg.generated
     */
    public void setJrid(String jrid) {
        this.jrid = jrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrecode.jobid
     *
     * @return the value of jrecode.jobid
     *
     * @mbg.generated
     */
    public String getJobid() {
        return jobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrecode.jobid
     *
     * @param jobid the value for jrecode.jobid
     *
     * @mbg.generated
     */
    public void setJobid(String jobid) {
        this.jobid = jobid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrecode.sendid
     *
     * @return the value of jrecode.sendid
     *
     * @mbg.generated
     */
    public String getSendid() {
        return sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrecode.sendid
     *
     * @param sendid the value for jrecode.sendid
     *
     * @mbg.generated
     */
    public void setSendid(String sendid) {
        this.sendid = sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrecode.status
     *
     * @return the value of jrecode.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrecode.status
     *
     * @param status the value for jrecode.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrecode.style
     *
     * @return the value of jrecode.style
     *
     * @mbg.generated
     */
    public String getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrecode.style
     *
     * @param style the value for jrecode.style
     *
     * @mbg.generated
     */
    public void setStyle(String style) {
        this.style = style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrecode.modifier
     *
     * @return the value of jrecode.modifier
     *
     * @mbg.generated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrecode.modifier
     *
     * @param modifier the value for jrecode.modifier
     *
     * @mbg.generated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrecode.modifytime
     *
     * @return the value of jrecode.modifytime
     *
     * @mbg.generated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrecode.modifytime
     *
     * @param modifytime the value for jrecode.modifytime
     *
     * @mbg.generated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrecode.creator
     *
     * @return the value of jrecode.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrecode.creator
     *
     * @param creator the value for jrecode.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrecode.createtime
     *
     * @return the value of jrecode.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrecode.createtime
     *
     * @param createtime the value for jrecode.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrecode.blank1
     *
     * @return the value of jrecode.blank1
     *
     * @mbg.generated
     */
    public String getBlank1() {
        return blank1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrecode.blank1
     *
     * @param blank1 the value for jrecode.blank1
     *
     * @mbg.generated
     */
    public void setBlank1(String blank1) {
        this.blank1 = blank1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrecode.blank2
     *
     * @return the value of jrecode.blank2
     *
     * @mbg.generated
     */
    public String getBlank2() {
        return blank2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrecode.blank2
     *
     * @param blank2 the value for jrecode.blank2
     *
     * @mbg.generated
     */
    public void setBlank2(String blank2) {
        this.blank2 = blank2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrecode.blank3
     *
     * @return the value of jrecode.blank3
     *
     * @mbg.generated
     */
    public String getBlank3() {
        return blank3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrecode.blank3
     *
     * @param blank3 the value for jrecode.blank3
     *
     * @mbg.generated
     */
    public void setBlank3(String blank3) {
        this.blank3 = blank3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column jrecode.blank4
     *
     * @return the value of jrecode.blank4
     *
     * @mbg.generated
     */
    public String getBlank4() {
        return blank4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column jrecode.blank4
     *
     * @param blank4 the value for jrecode.blank4
     *
     * @mbg.generated
     */
    public void setBlank4(String blank4) {
        this.blank4 = blank4;
    }
}