package com.lgw.po;

import java.util.Date;

public class Rsend {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rsend.sendid
     *
     * @mbg.generated
     */
    private String sendid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rsend.rid
     *
     * @mbg.generated
     */
    private String rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rsend.jrid
     *
     * @mbg.generated
     */
    private String jrid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rsend.modifier
     *
     * @mbg.generated
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rsend.modifytime
     *
     * @mbg.generated
     */
    private Date modifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rsend.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rsend.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rsend.blank1
     *
     * @mbg.generated
     */
    private String blank1;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rsend.blank2
     *
     * @mbg.generated
     */
    private String blank2;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rsend.blank3
     *
     * @mbg.generated
     */
    private String blank3;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rsend.blank4
     *
     * @mbg.generated
     */
    private String blank4;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsend.sendid
     *
     * @return the value of rsend.sendid
     *
     * @mbg.generated
     */
    public String getSendid() {
        return sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsend.sendid
     *
     * @param sendid the value for rsend.sendid
     *
     * @mbg.generated
     */
    public void setSendid(String sendid) {
        this.sendid = sendid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsend.rid
     *
     * @return the value of rsend.rid
     *
     * @mbg.generated
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsend.rid
     *
     * @param rid the value for rsend.rid
     *
     * @mbg.generated
     */
    public void setRid(String rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsend.jrid
     *
     * @return the value of rsend.jrid
     *
     * @mbg.generated
     */
    public String getJrid() {
        return jrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsend.jrid
     *
     * @param jrid the value for rsend.jrid
     *
     * @mbg.generated
     */
    public void setJrid(String jrid) {
        this.jrid = jrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsend.modifier
     *
     * @return the value of rsend.modifier
     *
     * @mbg.generated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsend.modifier
     *
     * @param modifier the value for rsend.modifier
     *
     * @mbg.generated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsend.modifytime
     *
     * @return the value of rsend.modifytime
     *
     * @mbg.generated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsend.modifytime
     *
     * @param modifytime the value for rsend.modifytime
     *
     * @mbg.generated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsend.creator
     *
     * @return the value of rsend.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsend.creator
     *
     * @param creator the value for rsend.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsend.createtime
     *
     * @return the value of rsend.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsend.createtime
     *
     * @param createtime the value for rsend.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsend.blank1
     *
     * @return the value of rsend.blank1
     *
     * @mbg.generated
     */
    public String getBlank1() {
        return blank1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsend.blank1
     *
     * @param blank1 the value for rsend.blank1
     *
     * @mbg.generated
     */
    public void setBlank1(String blank1) {
        this.blank1 = blank1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsend.blank2
     *
     * @return the value of rsend.blank2
     *
     * @mbg.generated
     */
    public String getBlank2() {
        return blank2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsend.blank2
     *
     * @param blank2 the value for rsend.blank2
     *
     * @mbg.generated
     */
    public void setBlank2(String blank2) {
        this.blank2 = blank2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsend.blank3
     *
     * @return the value of rsend.blank3
     *
     * @mbg.generated
     */
    public String getBlank3() {
        return blank3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsend.blank3
     *
     * @param blank3 the value for rsend.blank3
     *
     * @mbg.generated
     */
    public void setBlank3(String blank3) {
        this.blank3 = blank3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rsend.blank4
     *
     * @return the value of rsend.blank4
     *
     * @mbg.generated
     */
    public String getBlank4() {
        return blank4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rsend.blank4
     *
     * @param blank4 the value for rsend.blank4
     *
     * @mbg.generated
     */
    public void setBlank4(String blank4) {
        this.blank4 = blank4;
    }
}