package com.lgw.po;

import java.util.Date;

public class Salary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_salary.sid
     *
     * @mbg.generated
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_salary.salary
     *
     * @mbg.generated
     */
    private String salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_salary.xmodifier
     *
     * @mbg.generated
     */
    private String xmodifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_salary.xmodifiytime
     *
     * @mbg.generated
     */
    private Date xmodifiytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_salary.xcreator
     *
     * @mbg.generated
     */
    private String xcreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_salary.xcreatetime
     *
     * @mbg.generated
     */
    private Date xcreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_salary.sid
     *
     * @return the value of b_salary.sid
     *
     * @mbg.generated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_salary.sid
     *
     * @param sid the value for b_salary.sid
     *
     * @mbg.generated
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_salary.salary
     *
     * @return the value of b_salary.salary
     *
     * @mbg.generated
     */
    public String getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_salary.salary
     *
     * @param salary the value for b_salary.salary
     *
     * @mbg.generated
     */
    public void setSalary(String salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_salary.xmodifier
     *
     * @return the value of b_salary.xmodifier
     *
     * @mbg.generated
     */
    public String getXmodifier() {
        return xmodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_salary.xmodifier
     *
     * @param xmodifier the value for b_salary.xmodifier
     *
     * @mbg.generated
     */
    public void setXmodifier(String xmodifier) {
        this.xmodifier = xmodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_salary.xmodifiytime
     *
     * @return the value of b_salary.xmodifiytime
     *
     * @mbg.generated
     */
    public Date getXmodifiytime() {
        return xmodifiytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_salary.xmodifiytime
     *
     * @param xmodifiytime the value for b_salary.xmodifiytime
     *
     * @mbg.generated
     */
    public void setXmodifiytime(Date xmodifiytime) {
        this.xmodifiytime = xmodifiytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_salary.xcreator
     *
     * @return the value of b_salary.xcreator
     *
     * @mbg.generated
     */
    public String getXcreator() {
        return xcreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_salary.xcreator
     *
     * @param xcreator the value for b_salary.xcreator
     *
     * @mbg.generated
     */
    public void setXcreator(String xcreator) {
        this.xcreator = xcreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_salary.xcreatetime
     *
     * @return the value of b_salary.xcreatetime
     *
     * @mbg.generated
     */
    public Date getXcreatetime() {
        return xcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_salary.xcreatetime
     *
     * @param xcreatetime the value for b_salary.xcreatetime
     *
     * @mbg.generated
     */
    public void setXcreatetime(Date xcreatetime) {
        this.xcreatetime = xcreatetime;
    }
}