package com.lgw.po;

import java.util.Date;

public class Scale {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_scale.sid
     *
     * @mbg.generated
     */
    private String sid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_scale.scontext
     *
     * @mbg.generated
     */
    private String scontext;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_scale.xmodifier
     *
     * @mbg.generated
     */
    private String xmodifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_scale.xmodifiytime
     *
     * @mbg.generated
     */
    private Date xmodifiytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_scale.xcreator
     *
     * @mbg.generated
     */
    private String xcreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_scale.xcreatetime
     *
     * @mbg.generated
     */
    private Date xcreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_scale.sid
     *
     * @return the value of b_scale.sid
     *
     * @mbg.generated
     */
    public String getSid() {
        return sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_scale.sid
     *
     * @param sid the value for b_scale.sid
     *
     * @mbg.generated
     */
    public void setSid(String sid) {
        this.sid = sid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_scale.scontext
     *
     * @return the value of b_scale.scontext
     *
     * @mbg.generated
     */
    public String getScontext() {
        return scontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_scale.scontext
     *
     * @param scontext the value for b_scale.scontext
     *
     * @mbg.generated
     */
    public void setScontext(String scontext) {
        this.scontext = scontext;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_scale.xmodifier
     *
     * @return the value of b_scale.xmodifier
     *
     * @mbg.generated
     */
    public String getXmodifier() {
        return xmodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_scale.xmodifier
     *
     * @param xmodifier the value for b_scale.xmodifier
     *
     * @mbg.generated
     */
    public void setXmodifier(String xmodifier) {
        this.xmodifier = xmodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_scale.xmodifiytime
     *
     * @return the value of b_scale.xmodifiytime
     *
     * @mbg.generated
     */
    public Date getXmodifiytime() {
        return xmodifiytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_scale.xmodifiytime
     *
     * @param xmodifiytime the value for b_scale.xmodifiytime
     *
     * @mbg.generated
     */
    public void setXmodifiytime(Date xmodifiytime) {
        this.xmodifiytime = xmodifiytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_scale.xcreator
     *
     * @return the value of b_scale.xcreator
     *
     * @mbg.generated
     */
    public String getXcreator() {
        return xcreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_scale.xcreator
     *
     * @param xcreator the value for b_scale.xcreator
     *
     * @mbg.generated
     */
    public void setXcreator(String xcreator) {
        this.xcreator = xcreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_scale.xcreatetime
     *
     * @return the value of b_scale.xcreatetime
     *
     * @mbg.generated
     */
    public Date getXcreatetime() {
        return xcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_scale.xcreatetime
     *
     * @param xcreatetime the value for b_scale.xcreatetime
     *
     * @mbg.generated
     */
    public void setXcreatetime(Date xcreatetime) {
        this.xcreatetime = xcreatetime;
    }
}