package com.lgw.po;

import java.util.Date;

public class Stage {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_stage.stid
     *
     * @mbg.generated
     */
    private String stid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_stage.stname
     *
     * @mbg.generated
     */
    private String stname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_stage.xmodifier
     *
     * @mbg.generated
     */
    private String xmodifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_stage.xmodifiytime
     *
     * @mbg.generated
     */
    private Date xmodifiytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_stage.xcreator
     *
     * @mbg.generated
     */
    private String xcreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_stage.xcreatetime
     *
     * @mbg.generated
     */
    private Date xcreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_stage.stid
     *
     * @return the value of b_stage.stid
     *
     * @mbg.generated
     */
    public String getStid() {
        return stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_stage.stid
     *
     * @param stid the value for b_stage.stid
     *
     * @mbg.generated
     */
    public void setStid(String stid) {
        this.stid = stid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_stage.stname
     *
     * @return the value of b_stage.stname
     *
     * @mbg.generated
     */
    public String getStname() {
        return stname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_stage.stname
     *
     * @param stname the value for b_stage.stname
     *
     * @mbg.generated
     */
    public void setStname(String stname) {
        this.stname = stname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_stage.xmodifier
     *
     * @return the value of b_stage.xmodifier
     *
     * @mbg.generated
     */
    public String getXmodifier() {
        return xmodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_stage.xmodifier
     *
     * @param xmodifier the value for b_stage.xmodifier
     *
     * @mbg.generated
     */
    public void setXmodifier(String xmodifier) {
        this.xmodifier = xmodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_stage.xmodifiytime
     *
     * @return the value of b_stage.xmodifiytime
     *
     * @mbg.generated
     */
    public Date getXmodifiytime() {
        return xmodifiytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_stage.xmodifiytime
     *
     * @param xmodifiytime the value for b_stage.xmodifiytime
     *
     * @mbg.generated
     */
    public void setXmodifiytime(Date xmodifiytime) {
        this.xmodifiytime = xmodifiytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_stage.xcreator
     *
     * @return the value of b_stage.xcreator
     *
     * @mbg.generated
     */
    public String getXcreator() {
        return xcreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_stage.xcreator
     *
     * @param xcreator the value for b_stage.xcreator
     *
     * @mbg.generated
     */
    public void setXcreator(String xcreator) {
        this.xcreator = xcreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_stage.xcreatetime
     *
     * @return the value of b_stage.xcreatetime
     *
     * @mbg.generated
     */
    public Date getXcreatetime() {
        return xcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_stage.xcreatetime
     *
     * @param xcreatetime the value for b_stage.xcreatetime
     *
     * @mbg.generated
     */
    public void setXcreatetime(Date xcreatetime) {
        this.xcreatetime = xcreatetime;
    }
}