package com.lgw.po;

import java.util.Date;

public class Tag {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_tag.tid
     *
     * @mbg.generated
     */
    private String tid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_tag.b_t_tid
     *
     * @mbg.generated
     */
    private String bTTid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_tag.tname
     *
     * @mbg.generated
     */
    private String tname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_tag.isshow
     *
     * @mbg.generated
     */
    private Integer isshow;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_tag.xmodifier
     *
     * @mbg.generated
     */
    private String xmodifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_tag.xmodifiytime
     *
     * @mbg.generated
     */
    private Date xmodifiytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_tag.xcreator
     *
     * @mbg.generated
     */
    private String xcreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_tag.xcreatetime
     *
     * @mbg.generated
     */
    private Date xcreatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_tag.tid
     *
     * @return the value of b_tag.tid
     *
     * @mbg.generated
     */
    public String getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_tag.tid
     *
     * @param tid the value for b_tag.tid
     *
     * @mbg.generated
     */
    public void setTid(String tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_tag.b_t_tid
     *
     * @return the value of b_tag.b_t_tid
     *
     * @mbg.generated
     */
    public String getbTTid() {
        return bTTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_tag.b_t_tid
     *
     * @param bTTid the value for b_tag.b_t_tid
     *
     * @mbg.generated
     */
    public void setbTTid(String bTTid) {
        this.bTTid = bTTid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_tag.tname
     *
     * @return the value of b_tag.tname
     *
     * @mbg.generated
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_tag.tname
     *
     * @param tname the value for b_tag.tname
     *
     * @mbg.generated
     */
    public void setTname(String tname) {
        this.tname = tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_tag.isshow
     *
     * @return the value of b_tag.isshow
     *
     * @mbg.generated
     */
    public Integer getIsshow() {
        return isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_tag.isshow
     *
     * @param isshow the value for b_tag.isshow
     *
     * @mbg.generated
     */
    public void setIsshow(Integer isshow) {
        this.isshow = isshow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_tag.xmodifier
     *
     * @return the value of b_tag.xmodifier
     *
     * @mbg.generated
     */
    public String getXmodifier() {
        return xmodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_tag.xmodifier
     *
     * @param xmodifier the value for b_tag.xmodifier
     *
     * @mbg.generated
     */
    public void setXmodifier(String xmodifier) {
        this.xmodifier = xmodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_tag.xmodifiytime
     *
     * @return the value of b_tag.xmodifiytime
     *
     * @mbg.generated
     */
    public Date getXmodifiytime() {
        return xmodifiytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_tag.xmodifiytime
     *
     * @param xmodifiytime the value for b_tag.xmodifiytime
     *
     * @mbg.generated
     */
    public void setXmodifiytime(Date xmodifiytime) {
        this.xmodifiytime = xmodifiytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_tag.xcreator
     *
     * @return the value of b_tag.xcreator
     *
     * @mbg.generated
     */
    public String getXcreator() {
        return xcreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_tag.xcreator
     *
     * @param xcreator the value for b_tag.xcreator
     *
     * @mbg.generated
     */
    public void setXcreator(String xcreator) {
        this.xcreator = xcreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_tag.xcreatetime
     *
     * @return the value of b_tag.xcreatetime
     *
     * @mbg.generated
     */
    public Date getXcreatetime() {
        return xcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_tag.xcreatetime
     *
     * @param xcreatetime the value for b_tag.xcreatetime
     *
     * @mbg.generated
     */
    public void setXcreatetime(Date xcreatetime) {
        this.xcreatetime = xcreatetime;
    }
}