package com.lgw.po;

import java.util.Date;

public class Wantwork {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_wantwork.wid
     *
     * @mbg.generated
     */
    private String wid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_wantwork.rid
     *
     * @mbg.generated
     */
    private String rid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_wantwork.jobname
     *
     * @mbg.generated
     */
    private String jobname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_wantwork.jobtype
     *
     * @mbg.generated
     */
    private String jobtype;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_wantwork.city
     *
     * @mbg.generated
     */
    private String city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_wantwork.salary
     *
     * @mbg.generated
     */
    private String salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_wantwork.modifier
     *
     * @mbg.generated
     */
    private String modifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_wantwork.modifytime
     *
     * @mbg.generated
     */
    private Date modifytime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_wantwork.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_wantwork.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column p_wantwork.context
     *
     * @mbg.generated
     */
    private String context;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_wantwork.wid
     *
     * @return the value of p_wantwork.wid
     *
     * @mbg.generated
     */
    public String getWid() {
        return wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_wantwork.wid
     *
     * @param wid the value for p_wantwork.wid
     *
     * @mbg.generated
     */
    public void setWid(String wid) {
        this.wid = wid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_wantwork.rid
     *
     * @return the value of p_wantwork.rid
     *
     * @mbg.generated
     */
    public String getRid() {
        return rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_wantwork.rid
     *
     * @param rid the value for p_wantwork.rid
     *
     * @mbg.generated
     */
    public void setRid(String rid) {
        this.rid = rid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_wantwork.jobname
     *
     * @return the value of p_wantwork.jobname
     *
     * @mbg.generated
     */
    public String getJobname() {
        return jobname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_wantwork.jobname
     *
     * @param jobname the value for p_wantwork.jobname
     *
     * @mbg.generated
     */
    public void setJobname(String jobname) {
        this.jobname = jobname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_wantwork.jobtype
     *
     * @return the value of p_wantwork.jobtype
     *
     * @mbg.generated
     */
    public String getJobtype() {
        return jobtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_wantwork.jobtype
     *
     * @param jobtype the value for p_wantwork.jobtype
     *
     * @mbg.generated
     */
    public void setJobtype(String jobtype) {
        this.jobtype = jobtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_wantwork.city
     *
     * @return the value of p_wantwork.city
     *
     * @mbg.generated
     */
    public String getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_wantwork.city
     *
     * @param city the value for p_wantwork.city
     *
     * @mbg.generated
     */
    public void setCity(String city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_wantwork.salary
     *
     * @return the value of p_wantwork.salary
     *
     * @mbg.generated
     */
    public String getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_wantwork.salary
     *
     * @param salary the value for p_wantwork.salary
     *
     * @mbg.generated
     */
    public void setSalary(String salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_wantwork.modifier
     *
     * @return the value of p_wantwork.modifier
     *
     * @mbg.generated
     */
    public String getModifier() {
        return modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_wantwork.modifier
     *
     * @param modifier the value for p_wantwork.modifier
     *
     * @mbg.generated
     */
    public void setModifier(String modifier) {
        this.modifier = modifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_wantwork.modifytime
     *
     * @return the value of p_wantwork.modifytime
     *
     * @mbg.generated
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_wantwork.modifytime
     *
     * @param modifytime the value for p_wantwork.modifytime
     *
     * @mbg.generated
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_wantwork.creator
     *
     * @return the value of p_wantwork.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_wantwork.creator
     *
     * @param creator the value for p_wantwork.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_wantwork.createtime
     *
     * @return the value of p_wantwork.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_wantwork.createtime
     *
     * @param createtime the value for p_wantwork.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column p_wantwork.context
     *
     * @return the value of p_wantwork.context
     *
     * @mbg.generated
     */
    public String getContext() {
        return context;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column p_wantwork.context
     *
     * @param context the value for p_wantwork.context
     *
     * @mbg.generated
     */
    public void setContext(String context) {
        this.context = context;
    }
}