package com.lgw.po;

import java.util.Date;

public class Xueli {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_xueli.xid
     *
     * @mbg.generated
     */
    private String xid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_xueli.xname
     *
     * @mbg.generated
     */
    private String xname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_xueli.xcreator
     *
     * @mbg.generated
     */
    private String xcreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_xueli.xcreatetime
     *
     * @mbg.generated
     */
    private Date xcreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_xueli.xmodifier
     *
     * @mbg.generated
     */
    private String xmodifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_xueli.xmodifiytime
     *
     * @mbg.generated
     */
    private Date xmodifiytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_xueli.xid
     *
     * @return the value of b_xueli.xid
     *
     * @mbg.generated
     */
    public String getXid() {
        return xid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_xueli.xid
     *
     * @param xid the value for b_xueli.xid
     *
     * @mbg.generated
     */
    public void setXid(String xid) {
        this.xid = xid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_xueli.xname
     *
     * @return the value of b_xueli.xname
     *
     * @mbg.generated
     */
    public String getXname() {
        return xname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_xueli.xname
     *
     * @param xname the value for b_xueli.xname
     *
     * @mbg.generated
     */
    public void setXname(String xname) {
        this.xname = xname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_xueli.xcreator
     *
     * @return the value of b_xueli.xcreator
     *
     * @mbg.generated
     */
    public String getXcreator() {
        return xcreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_xueli.xcreator
     *
     * @param xcreator the value for b_xueli.xcreator
     *
     * @mbg.generated
     */
    public void setXcreator(String xcreator) {
        this.xcreator = xcreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_xueli.xcreatetime
     *
     * @return the value of b_xueli.xcreatetime
     *
     * @mbg.generated
     */
    public Date getXcreatetime() {
        return xcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_xueli.xcreatetime
     *
     * @param xcreatetime the value for b_xueli.xcreatetime
     *
     * @mbg.generated
     */
    public void setXcreatetime(Date xcreatetime) {
        this.xcreatetime = xcreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_xueli.xmodifier
     *
     * @return the value of b_xueli.xmodifier
     *
     * @mbg.generated
     */
    public String getXmodifier() {
        return xmodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_xueli.xmodifier
     *
     * @param xmodifier the value for b_xueli.xmodifier
     *
     * @mbg.generated
     */
    public void setXmodifier(String xmodifier) {
        this.xmodifier = xmodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_xueli.xmodifiytime
     *
     * @return the value of b_xueli.xmodifiytime
     *
     * @mbg.generated
     */
    public Date getXmodifiytime() {
        return xmodifiytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_xueli.xmodifiytime
     *
     * @param xmodifiytime the value for b_xueli.xmodifiytime
     *
     * @mbg.generated
     */
    public void setXmodifiytime(Date xmodifiytime) {
        this.xmodifiytime = xmodifiytime;
    }
}