package com.lgw.po;

import java.util.Date;

public class Year {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_year.yid
     *
     * @mbg.generated
     */
    private String yid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_year.yname
     *
     * @mbg.generated
     */
    private String yname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_year.ycreator
     *
     * @mbg.generated
     */
    private String ycreator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_year.ycreatetime
     *
     * @mbg.generated
     */
    private Date ycreatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_year.ymodifier
     *
     * @mbg.generated
     */
    private String ymodifier;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column b_year.ymodifytime
     *
     * @mbg.generated
     */
    private Date ymodifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_year.yid
     *
     * @return the value of b_year.yid
     *
     * @mbg.generated
     */
    public String getYid() {
        return yid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_year.yid
     *
     * @param yid the value for b_year.yid
     *
     * @mbg.generated
     */
    public void setYid(String yid) {
        this.yid = yid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_year.yname
     *
     * @return the value of b_year.yname
     *
     * @mbg.generated
     */
    public String getYname() {
        return yname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_year.yname
     *
     * @param yname the value for b_year.yname
     *
     * @mbg.generated
     */
    public void setYname(String yname) {
        this.yname = yname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_year.ycreator
     *
     * @return the value of b_year.ycreator
     *
     * @mbg.generated
     */
    public String getYcreator() {
        return ycreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_year.ycreator
     *
     * @param ycreator the value for b_year.ycreator
     *
     * @mbg.generated
     */
    public void setYcreator(String ycreator) {
        this.ycreator = ycreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_year.ycreatetime
     *
     * @return the value of b_year.ycreatetime
     *
     * @mbg.generated
     */
    public Date getYcreatetime() {
        return ycreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_year.ycreatetime
     *
     * @param ycreatetime the value for b_year.ycreatetime
     *
     * @mbg.generated
     */
    public void setYcreatetime(Date ycreatetime) {
        this.ycreatetime = ycreatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_year.ymodifier
     *
     * @return the value of b_year.ymodifier
     *
     * @mbg.generated
     */
    public String getYmodifier() {
        return ymodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_year.ymodifier
     *
     * @param ymodifier the value for b_year.ymodifier
     *
     * @mbg.generated
     */
    public void setYmodifier(String ymodifier) {
        this.ymodifier = ymodifier;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column b_year.ymodifytime
     *
     * @return the value of b_year.ymodifytime
     *
     * @mbg.generated
     */
    public Date getYmodifytime() {
        return ymodifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column b_year.ymodifytime
     *
     * @param ymodifytime the value for b_year.ymodifytime
     *
     * @mbg.generated
     */
    public void setYmodifytime(Date ymodifytime) {
        this.ymodifytime = ymodifytime;
    }
}