package com.lgw.po;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class YearExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_year
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_year
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table b_year
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_year
     *
     * @mbg.generated
     */
    public YearExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_year
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_year
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_year
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_year
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_year
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_year
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_year
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_year
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_year
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table b_year
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_year
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCTime(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value.getTime()), property);
        }

        protected void addCriterionForJDBCTime(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Time> timeList = new ArrayList<java.sql.Time>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                timeList.add(new java.sql.Time(iter.next().getTime()));
            }
            addCriterion(condition, timeList, property);
        }

        protected void addCriterionForJDBCTime(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Time(value1.getTime()), new java.sql.Time(value2.getTime()), property);
        }

        public Criteria andYidIsNull() {
            addCriterion("yid is null");
            return (Criteria) this;
        }

        public Criteria andYidIsNotNull() {
            addCriterion("yid is not null");
            return (Criteria) this;
        }

        public Criteria andYidEqualTo(String value) {
            addCriterion("yid =", value, "yid");
            return (Criteria) this;
        }

        public Criteria andYidNotEqualTo(String value) {
            addCriterion("yid <>", value, "yid");
            return (Criteria) this;
        }

        public Criteria andYidGreaterThan(String value) {
            addCriterion("yid >", value, "yid");
            return (Criteria) this;
        }

        public Criteria andYidGreaterThanOrEqualTo(String value) {
            addCriterion("yid >=", value, "yid");
            return (Criteria) this;
        }

        public Criteria andYidLessThan(String value) {
            addCriterion("yid <", value, "yid");
            return (Criteria) this;
        }

        public Criteria andYidLessThanOrEqualTo(String value) {
            addCriterion("yid <=", value, "yid");
            return (Criteria) this;
        }

        public Criteria andYidLike(String value) {
            addCriterion("yid like", value, "yid");
            return (Criteria) this;
        }

        public Criteria andYidNotLike(String value) {
            addCriterion("yid not like", value, "yid");
            return (Criteria) this;
        }

        public Criteria andYidIn(List<String> values) {
            addCriterion("yid in", values, "yid");
            return (Criteria) this;
        }

        public Criteria andYidNotIn(List<String> values) {
            addCriterion("yid not in", values, "yid");
            return (Criteria) this;
        }

        public Criteria andYidBetween(String value1, String value2) {
            addCriterion("yid between", value1, value2, "yid");
            return (Criteria) this;
        }

        public Criteria andYidNotBetween(String value1, String value2) {
            addCriterion("yid not between", value1, value2, "yid");
            return (Criteria) this;
        }

        public Criteria andYnameIsNull() {
            addCriterion("yname is null");
            return (Criteria) this;
        }

        public Criteria andYnameIsNotNull() {
            addCriterion("yname is not null");
            return (Criteria) this;
        }

        public Criteria andYnameEqualTo(String value) {
            addCriterion("yname =", value, "yname");
            return (Criteria) this;
        }

        public Criteria andYnameNotEqualTo(String value) {
            addCriterion("yname <>", value, "yname");
            return (Criteria) this;
        }

        public Criteria andYnameGreaterThan(String value) {
            addCriterion("yname >", value, "yname");
            return (Criteria) this;
        }

        public Criteria andYnameGreaterThanOrEqualTo(String value) {
            addCriterion("yname >=", value, "yname");
            return (Criteria) this;
        }

        public Criteria andYnameLessThan(String value) {
            addCriterion("yname <", value, "yname");
            return (Criteria) this;
        }

        public Criteria andYnameLessThanOrEqualTo(String value) {
            addCriterion("yname <=", value, "yname");
            return (Criteria) this;
        }

        public Criteria andYnameLike(String value) {
            addCriterion("yname like", value, "yname");
            return (Criteria) this;
        }

        public Criteria andYnameNotLike(String value) {
            addCriterion("yname not like", value, "yname");
            return (Criteria) this;
        }

        public Criteria andYnameIn(List<String> values) {
            addCriterion("yname in", values, "yname");
            return (Criteria) this;
        }

        public Criteria andYnameNotIn(List<String> values) {
            addCriterion("yname not in", values, "yname");
            return (Criteria) this;
        }

        public Criteria andYnameBetween(String value1, String value2) {
            addCriterion("yname between", value1, value2, "yname");
            return (Criteria) this;
        }

        public Criteria andYnameNotBetween(String value1, String value2) {
            addCriterion("yname not between", value1, value2, "yname");
            return (Criteria) this;
        }

        public Criteria andYcreatorIsNull() {
            addCriterion("ycreator is null");
            return (Criteria) this;
        }

        public Criteria andYcreatorIsNotNull() {
            addCriterion("ycreator is not null");
            return (Criteria) this;
        }

        public Criteria andYcreatorEqualTo(String value) {
            addCriterion("ycreator =", value, "ycreator");
            return (Criteria) this;
        }

        public Criteria andYcreatorNotEqualTo(String value) {
            addCriterion("ycreator <>", value, "ycreator");
            return (Criteria) this;
        }

        public Criteria andYcreatorGreaterThan(String value) {
            addCriterion("ycreator >", value, "ycreator");
            return (Criteria) this;
        }

        public Criteria andYcreatorGreaterThanOrEqualTo(String value) {
            addCriterion("ycreator >=", value, "ycreator");
            return (Criteria) this;
        }

        public Criteria andYcreatorLessThan(String value) {
            addCriterion("ycreator <", value, "ycreator");
            return (Criteria) this;
        }

        public Criteria andYcreatorLessThanOrEqualTo(String value) {
            addCriterion("ycreator <=", value, "ycreator");
            return (Criteria) this;
        }

        public Criteria andYcreatorLike(String value) {
            addCriterion("ycreator like", value, "ycreator");
            return (Criteria) this;
        }

        public Criteria andYcreatorNotLike(String value) {
            addCriterion("ycreator not like", value, "ycreator");
            return (Criteria) this;
        }

        public Criteria andYcreatorIn(List<String> values) {
            addCriterion("ycreator in", values, "ycreator");
            return (Criteria) this;
        }

        public Criteria andYcreatorNotIn(List<String> values) {
            addCriterion("ycreator not in", values, "ycreator");
            return (Criteria) this;
        }

        public Criteria andYcreatorBetween(String value1, String value2) {
            addCriterion("ycreator between", value1, value2, "ycreator");
            return (Criteria) this;
        }

        public Criteria andYcreatorNotBetween(String value1, String value2) {
            addCriterion("ycreator not between", value1, value2, "ycreator");
            return (Criteria) this;
        }

        public Criteria andYcreatetimeIsNull() {
            addCriterion("ycreatetime is null");
            return (Criteria) this;
        }

        public Criteria andYcreatetimeIsNotNull() {
            addCriterion("ycreatetime is not null");
            return (Criteria) this;
        }

        public Criteria andYcreatetimeEqualTo(Date value) {
            addCriterionForJDBCTime("ycreatetime =", value, "ycreatetime");
            return (Criteria) this;
        }

        public Criteria andYcreatetimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("ycreatetime <>", value, "ycreatetime");
            return (Criteria) this;
        }

        public Criteria andYcreatetimeGreaterThan(Date value) {
            addCriterionForJDBCTime("ycreatetime >", value, "ycreatetime");
            return (Criteria) this;
        }

        public Criteria andYcreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("ycreatetime >=", value, "ycreatetime");
            return (Criteria) this;
        }

        public Criteria andYcreatetimeLessThan(Date value) {
            addCriterionForJDBCTime("ycreatetime <", value, "ycreatetime");
            return (Criteria) this;
        }

        public Criteria andYcreatetimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("ycreatetime <=", value, "ycreatetime");
            return (Criteria) this;
        }

        public Criteria andYcreatetimeIn(List<Date> values) {
            addCriterionForJDBCTime("ycreatetime in", values, "ycreatetime");
            return (Criteria) this;
        }

        public Criteria andYcreatetimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("ycreatetime not in", values, "ycreatetime");
            return (Criteria) this;
        }

        public Criteria andYcreatetimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("ycreatetime between", value1, value2, "ycreatetime");
            return (Criteria) this;
        }

        public Criteria andYcreatetimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("ycreatetime not between", value1, value2, "ycreatetime");
            return (Criteria) this;
        }

        public Criteria andYmodifierIsNull() {
            addCriterion("ymodifier is null");
            return (Criteria) this;
        }

        public Criteria andYmodifierIsNotNull() {
            addCriterion("ymodifier is not null");
            return (Criteria) this;
        }

        public Criteria andYmodifierEqualTo(String value) {
            addCriterion("ymodifier =", value, "ymodifier");
            return (Criteria) this;
        }

        public Criteria andYmodifierNotEqualTo(String value) {
            addCriterion("ymodifier <>", value, "ymodifier");
            return (Criteria) this;
        }

        public Criteria andYmodifierGreaterThan(String value) {
            addCriterion("ymodifier >", value, "ymodifier");
            return (Criteria) this;
        }

        public Criteria andYmodifierGreaterThanOrEqualTo(String value) {
            addCriterion("ymodifier >=", value, "ymodifier");
            return (Criteria) this;
        }

        public Criteria andYmodifierLessThan(String value) {
            addCriterion("ymodifier <", value, "ymodifier");
            return (Criteria) this;
        }

        public Criteria andYmodifierLessThanOrEqualTo(String value) {
            addCriterion("ymodifier <=", value, "ymodifier");
            return (Criteria) this;
        }

        public Criteria andYmodifierLike(String value) {
            addCriterion("ymodifier like", value, "ymodifier");
            return (Criteria) this;
        }

        public Criteria andYmodifierNotLike(String value) {
            addCriterion("ymodifier not like", value, "ymodifier");
            return (Criteria) this;
        }

        public Criteria andYmodifierIn(List<String> values) {
            addCriterion("ymodifier in", values, "ymodifier");
            return (Criteria) this;
        }

        public Criteria andYmodifierNotIn(List<String> values) {
            addCriterion("ymodifier not in", values, "ymodifier");
            return (Criteria) this;
        }

        public Criteria andYmodifierBetween(String value1, String value2) {
            addCriterion("ymodifier between", value1, value2, "ymodifier");
            return (Criteria) this;
        }

        public Criteria andYmodifierNotBetween(String value1, String value2) {
            addCriterion("ymodifier not between", value1, value2, "ymodifier");
            return (Criteria) this;
        }

        public Criteria andYmodifytimeIsNull() {
            addCriterion("ymodifytime is null");
            return (Criteria) this;
        }

        public Criteria andYmodifytimeIsNotNull() {
            addCriterion("ymodifytime is not null");
            return (Criteria) this;
        }

        public Criteria andYmodifytimeEqualTo(Date value) {
            addCriterionForJDBCTime("ymodifytime =", value, "ymodifytime");
            return (Criteria) this;
        }

        public Criteria andYmodifytimeNotEqualTo(Date value) {
            addCriterionForJDBCTime("ymodifytime <>", value, "ymodifytime");
            return (Criteria) this;
        }

        public Criteria andYmodifytimeGreaterThan(Date value) {
            addCriterionForJDBCTime("ymodifytime >", value, "ymodifytime");
            return (Criteria) this;
        }

        public Criteria andYmodifytimeGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("ymodifytime >=", value, "ymodifytime");
            return (Criteria) this;
        }

        public Criteria andYmodifytimeLessThan(Date value) {
            addCriterionForJDBCTime("ymodifytime <", value, "ymodifytime");
            return (Criteria) this;
        }

        public Criteria andYmodifytimeLessThanOrEqualTo(Date value) {
            addCriterionForJDBCTime("ymodifytime <=", value, "ymodifytime");
            return (Criteria) this;
        }

        public Criteria andYmodifytimeIn(List<Date> values) {
            addCriterionForJDBCTime("ymodifytime in", values, "ymodifytime");
            return (Criteria) this;
        }

        public Criteria andYmodifytimeNotIn(List<Date> values) {
            addCriterionForJDBCTime("ymodifytime not in", values, "ymodifytime");
            return (Criteria) this;
        }

        public Criteria andYmodifytimeBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("ymodifytime between", value1, value2, "ymodifytime");
            return (Criteria) this;
        }

        public Criteria andYmodifytimeNotBetween(Date value1, Date value2) {
            addCriterionForJDBCTime("ymodifytime not between", value1, value2, "ymodifytime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_year
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table b_year
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}