package com.lgw.dao;

import com.lgw.base.BaseMapper;
import com.lgw.po.JobWithBLOBs;
import org.apache.ibatis.annotations.Param;

public interface JobMapper<Job,JobExample,String> extends BaseMapper{
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_Job
     *
     * @mbg.generated
     */
    int insert(JobWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_Job
     *
     * @mbg.generated
     */
    int insertSelective(JobWithBLOBs record);
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_Job
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") JobWithBLOBs record, @Param("example") JobExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_Job
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(JobWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table p_Job
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(JobWithBLOBs record);


}