package com.demo.dao;

import com.demo.po.CloudCourse;
import com.demo.po.CloudCourseExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CloudCourseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course
     *
     * @mbg.generated
     */
    long countByExample(CloudCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course
     *
     * @mbg.generated
     */
    int deleteByExample(CloudCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course
     *
     * @mbg.generated
     */
    int insert(CloudCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course
     *
     * @mbg.generated
     */
    int insertSelective(CloudCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course
     *
     * @mbg.generated
     */
    List<CloudCourse> selectByExample(CloudCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course
     *
     * @mbg.generated
     */
    CloudCourse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CloudCourse record, @Param("example") CloudCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CloudCourse record, @Param("example") CloudCourseExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CloudCourse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CloudCourse record);
}