package com.demo.dao;

import com.demo.po.CloudCourseItem;
import com.demo.po.CloudCourseItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface CloudCourseItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course_item
     *
     * @mbg.generated
     */
    long countByExample(CloudCourseItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course_item
     *
     * @mbg.generated
     */
    int deleteByExample(CloudCourseItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course_item
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course_item
     *
     * @mbg.generated
     */
    int insert(CloudCourseItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course_item
     *
     * @mbg.generated
     */
    int insertSelective(CloudCourseItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course_item
     *
     * @mbg.generated
     */
    List<CloudCourseItem> selectByExample(CloudCourseItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course_item
     *
     * @mbg.generated
     */
    CloudCourseItem selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course_item
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") CloudCourseItem record, @Param("example") CloudCourseItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course_item
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") CloudCourseItem record, @Param("example") CloudCourseItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(CloudCourseItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table cloud_course_item
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(CloudCourseItem record);
}