package com.demo.po;

import java.util.Date;

public class CloudCourse {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_course.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_course.year
     *
     * @mbg.generated
     */
    private Integer year;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_course.term
     *
     * @mbg.generated
     */
    private Integer term;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_course.create_user
     *
     * @mbg.generated
     */
    private Long createUser;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_course.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_course.task_id
     *
     * @mbg.generated
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_course.run_id
     *
     * @mbg.generated
     */
    private Long runId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cloud_course.run_state
     *
     * @mbg.generated
     */
    private String runState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_course.id
     *
     * @return the value of cloud_course.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_course.id
     *
     * @param id the value for cloud_course.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_course.year
     *
     * @return the value of cloud_course.year
     *
     * @mbg.generated
     */
    public Integer getYear() {
        return year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_course.year
     *
     * @param year the value for cloud_course.year
     *
     * @mbg.generated
     */
    public void setYear(Integer year) {
        this.year = year;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_course.term
     *
     * @return the value of cloud_course.term
     *
     * @mbg.generated
     */
    public Integer getTerm() {
        return term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_course.term
     *
     * @param term the value for cloud_course.term
     *
     * @mbg.generated
     */
    public void setTerm(Integer term) {
        this.term = term;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_course.create_user
     *
     * @return the value of cloud_course.create_user
     *
     * @mbg.generated
     */
    public Long getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_course.create_user
     *
     * @param createUser the value for cloud_course.create_user
     *
     * @mbg.generated
     */
    public void setCreateUser(Long createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_course.create_time
     *
     * @return the value of cloud_course.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_course.create_time
     *
     * @param createTime the value for cloud_course.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_course.task_id
     *
     * @return the value of cloud_course.task_id
     *
     * @mbg.generated
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_course.task_id
     *
     * @param taskId the value for cloud_course.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_course.run_id
     *
     * @return the value of cloud_course.run_id
     *
     * @mbg.generated
     */
    public Long getRunId() {
        return runId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_course.run_id
     *
     * @param runId the value for cloud_course.run_id
     *
     * @mbg.generated
     */
    public void setRunId(Long runId) {
        this.runId = runId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cloud_course.run_state
     *
     * @return the value of cloud_course.run_state
     *
     * @mbg.generated
     */
    public String getRunState() {
        return runState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cloud_course.run_state
     *
     * @param runState the value for cloud_course.run_state
     *
     * @mbg.generated
     */
    public void setRunState(String runState) {
        this.runState = runState;
    }
}